[default]
appName = "gen-project-default"
addr = ":8088"
readTimeout = 10
writeTimeout = 10

[log]
level = "debug"

[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0
MaxIdel = 100
MaxActive = 4000
IdleTimeout = 180

[masterDB]
host = "127.0.0.1"
port = 54321
user = "postgres"
password = "123456"
db = "postgres"
MaxOpenConns = 1000
MaxIdleConns = 100